# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - todo

# some rules are only opt-in
opt_in_rules:
  - empty_count
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
#included:
  - SnSResKit/Classes/

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Example/

line_length:
  warning: 200
  error: 250